# Generated by Django 4.1.3 on 2022-11-02 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('explaination', models.TextField()),
                ('hdurl', models.TextField()),
                ('media_type', models.TextField()),
                ('urli', models.TextField()),
                ('apod_date', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Rovers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rover_name', models.TextField()),
                ('rover_landing_date', models.TextField()),
                ('rover_launching_date', models.TextField()),
                ('rover_status', models.TextField()),
                ('max_sol', models.TextField()),
                ('max_date', models.TextField()),
                ('total_photos', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=35)),
                ('email', models.EmailField(max_length=254)),
                ('hashed_pass', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genimages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.TextField()),
                ('camera', models.TextField()),
                ('image_earth_date', models.TextField()),
                ('gen_date', models.DateTimeField(auto_now_add=True)),
                ('rover_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imagegen.rovers')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imagegen.users')),
            ],
        ),
    ]
