# Generated by Django 4.1.3 on 2022-11-09 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagegen', '0004_rovers_first_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='genimages',
            name='image_api_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
