# Generated by Django 4.1.3 on 2022-11-11 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imagegen', '0005_genimages_image_api_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Genimages',
        ),
    ]
